version: '3.7'
services:
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #     - 1234:8080

    # postgres: 
    #     container_name: Postgres
    #     image: postgres
    #     environment: 
    #         POSTGRES_PASSWORD: postgres-payday
    #         POSTGRES_USER: postgres-payday
    #         POSTGRES_DB: payday
    #     volumes: 
    #         - ./pgdata:/var/lib/postgresql/data
    #     networks: 
    #         - backend
    #     ports: 
    #         - '5400:5400'
    
    mongo:
      container_name: Mongo
      image: mongo
      networks:
        - backend
      restart: always
      ports:
        - '27017:27017'
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: payday
        MONGO_INITDB_DATABASE: payday

  
    mongo-express:
      container_name: Mongo-Express
      image: mongo-express
      restart: always
      networks:
        - backend
      depends_on:
        - mongo
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: payday

    # PaydayBackend:
    #     container_name: Payday-Backend
    #     image: payday-backend
    #     build: 
    #         dockerfile: Dockerfile
    #         context: ./backend
    #     restart: always
    #     depends_on: 
    #       - mongo-express
    #     ports:
    #       - '8080:8080'
    #     env_file:
    #       - ./backend/.env
    #     networks:
    #       - backend
  
 
networks:
  backend:

